<?xml version="1.0"?>
<robot name="epipolar" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="M_PI" value="3.1415926535897931"/>
    <xacro:property name="SQRT" value="1.41421"/>
    <xacro:property name="radius" value="3"/>
    <xacro:property name="DEG2RAD" value="0.01745329251"/>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <link name="world"/>

    <link name="checkerboard_link">
       <visual>
            <geometry>
                <box size="0.001 0.9 0.7" />
            </geometry>
       </visual>
        <collision>
            <geometry>
                <box size="0.001 0.9 0.7" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
        </inertial>
    </link>

    <link name="camera_l_link">
        <visual>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
        </inertial>
    </link>

    <link name="camera_r_link">
        <visual>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
        </inertial>
    </link>





    <joint name="checkerboard_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="checkerboard_link"/>
    </joint>

    <joint name="camera_l_joint" type="fixed">
        <origin xyz="-${SQRT/2*radius} ${SQRT/2*radius} 0" rpy="0 0 ${-45*DEG2RAD}"/>
        <parent link="world"/>
        <child link="camera_l_link"/>
    </joint>

    <joint name="camera_r_joint" type="fixed">
        <origin xyz="-${SQRT/2*radius} -${SQRT/2*radius} 0" rpy="0 0 ${45*DEG2RAD}"/>
        <parent link="world"/>
        <child link="camera_r_link"/>
    </joint>


    <gazebo reference="checkerboard_link">
        <material>Checkerboard</material>
    </gazebo>

    <gazebo reference="fiducial_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="camera_l_link">
        <sensor type="camera" name="camera_l">
            <update_rate>30.0</update_rate>
            <visualize>1</visualize>
            <camera name="camera_l">
                <horizontal_fov>${M_PI/180.0*30.0}</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>720</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.0</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>camera_l</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_l</frameName>
                <hackBaseline>0.0</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0.0</Cx>
                <Cy>0.0</Cy>
                <focalLength>0.0</focalLength>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo reference="camera_r_link">
        <sensor type="camera" name="camera_r">
            <update_rate>30.0</update_rate>
            <visualize>1</visualize>
            <camera name="camera_r">
                <horizontal_fov>${M_PI/180.0*30.0}</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>720</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.0</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>camera_r</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_r</frameName>
                <hackBaseline>0.0</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0.0</Cx>
                <Cy>0.0</Cy>
                <focalLength>0.0</focalLength>
            </plugin>
        </sensor>
    </gazebo>
</robot>